# Welcome to Jekyll!
#
# more at https://jekyllrb.com/docs/home/
#
title: Unregulated Powersupply
email: unregulatedpowersupply@gmail.com
#description:
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://unregulatedpowersupply.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  UnregulatedPowersupply

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
